#ifndef SSPP_CONFIG_H
#define SSPP_CONFIG_H

#define SSPP_CONNECTION_WAIT_TIME 0.1
#define SSPP_MESSAGE_WAIT_TIME 0.001
#define SSPP_DEFAULT_TOPIC_SERVER "tcp://localhost:4567"
#define SSPP_READ_QUEUE_SIZE 100
#define SSPP_WRITE_QUEUE_SIZE 100

#endif
