controller_frequency: 5.0 
planner_frequency: 5.0  
planner_patience: 3.0  
controller_patience: 3.0 
recovery_behavior_enabled: false 
clearing_rotation_allowed: false

recovery_behaviors:
  - name: aggressive_reset
    type: clear_costmap_recovery/ClearCostmapRecovery

# Configuration for recovery behaviors
aggressive_reset:
  # When doing an aggressive reset, remove all voxels from the
  # costmap.
  reset_distance: 0.01

global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  static_map: false
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.05
  map_type: costmap 
  unknown_threshold: 10
  update_frequency: 5.0
  publish_frequency: 1.0
  transform_tolerance: 0.3
  inflation_radius: 0.5
  cost_scaling_factor: 10.0
  robot_radius: 0.5
  footprint: [[-0.2, -0.15], [-0.2, 0.15], [0.1, 0.15], [0.1, -0.15]]
  footprint_padding: 0.05
  raytrace_range: 1006.0
  obstacle_range: 2.5
  observation_sources: "laser_scan"
  laser_scan: { sensor_frame: /frame_laser_front, data_type: LaserScan, topic: /scan_front, marking: true, clearing: true, observation_persistence: 2.0 }
  ground_object_cloud:
    topic: /camera/depth/points
    data_type: PointCloud2
    expected_update_rate: 5.0
    sensor_frame: /camera_link
    observation_persistence: 15.0
    marking: true
    clearing: true
    max_obstacle_height: 0.5
    min_obstacle_height: 0.33 

local_costmap:
  global_frame: /map 
  #global_frame: odom 
  robot_base_frame: base_link
  static_map: false
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.05
  map_type: costmap
  unknown_threshold: 10
  update_frequency: 5.0
  publish_frequency: 1.0
  transform_tolerance: 0.5
  inflation_radius: 0.5
  cost_scaling_factor: 10.0
  robot_radius: 0.05
  footprint: [[-0.2, -0.15], [-0.2, 0.15], [0.1, 0.15], [0.1, -0.15]]
  footprint_padding: 0.01
  raytrace_range: 1006.0
  obstacle_range: 2.5
  #observation_sources: "laser_scan ground_object_cloud"
  observation_sources: "laser_scan"
  laser_scan: { sensor_frame: /frame_laser_front, data_type: LaserScan, topic: /scan_front, marking: true, clearing: true, observation_persistence: 2.0 }


#controller_frequency: 5
# Give the local planner only 5 seconds time to find a vaid control.
#base_local_planner: dwa_local_planner/DWAPlannerROS
base_local_planner: base_local_planner/TrajectoryPlannerROS
recovery_behaviors:
  - name: aggressive_reset
    type: clear_costmap_recovery/ClearCostmapRecovery

# Configuration for recovery behaviors
aggressive_reset:
  # When doing an aggressive reset, remove all voxels from the
  # costmap.
  reset_distance: 0.01

# We need to kape the min_in_place_rotational_vel since it is used by
# the rotate recovery.

TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.0
  max_vel_y: 0.9
  min_vel_y: -0.9
  max_vel_theta: 0.7
  min_vel_theta: -0.7
  max_rotational_vel: 0.7
  min_in_place_vel_theta: 0.7
  acc_lim_theta: 0.5
  acc_lim_x: 0.8
  acc_lim_y: 0.8

  holonomic_robot: true 
  yaw_goal_tolerance: 0.5
  xy_goal_tolerance: 0.25
  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  sim_time: 1.0
  heading_lookahead: 0.8
  oscillation_reset_dist: 0.25

  pdist_scale: 0.2
  gdist_scale: 0.2

  vx_samples: 6
  vtheta_samples: 20
  dwa: false

#NavfnROS:
#  default_tolerance: 0.5



