amcl:
  use_map_topic: false
  first_map_only: false
  odom_model_type: omni
  gui_publish_rate: 0.5
  laser_max_beams: 30
  laser_max_range: 3.0
  min_particles: 100
  max_particles: 1000
  kld_err: 0.05
  kld_z: 0.99
  odom_alpha1: 0.5
  odom_alpha2: 0.5
  odom_alpha3: 0.8
  odom_alpha4: 0.8
  odom_alpha5: 0.3
  laser_z_hit: 0.5
  laser_z_rand: 0.5
  laser_sigma_hit: 0.2
  laser_lambda_short: 0.1
  laser_model_type: likelihood_field 
  initial_cov_xx: 0.25
  initial_cov_yy: 0.25
  initial_cov_aa: 0.013
  laser_likelihood_max_dist: 2.0
  update_min_d: 0.25
  update_min_a: 0.25
  odom_frame_id: odom
  base_frame_id: base_link 
  global_frame_id: map
  resample_interval: 1
  transform_tolerance: 0.2
  recovery_alpha_slow: 0.0
  recovery_alpha_fast: 0.0
  save_pose_rate: -1.0 
