sample_poses_by_index:
- px: 1.0
  py: 0.5
  pz: 1.0
- px: 1.0
  py: 0.0
  pz: 0.0
- px: 2.0
  py: 0.5
  pz: 0.0
- px: 1.0
  py: 0.5
  pz: 0.0
- px: 0.0
  py: 0.0
  pz: 0.0
- px: 0.0
  py: 0.0
  pz: 0.0
